apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
  annotations:
    pod-url: "https://localhost:4500"
spec:
  containers:
    - name: kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      # liveness probe for health check
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
